### ISSUE TITLE
Sentry: Trying to get property of non-object in api::user::gdpr_export

### ISSUE THREAD

**Issue by thijsdortmann** [saproto/saproto#1003]
Looks (at first very quick glance) like the GDPR export doesn't handle it well when a user doesn't have any quotes. Might be an issue for other models as well.

https://sentry.io/organizations/sa-proto/issues/1245403566

**Comment by jonathanjuursema** [comment]
I'm not sure what it is. Sentry points to [here](https://github.com/saproto/saproto/blob/master/app/Http/Controllers/ApiController.php#L209) so I checked what happens if you have a like on a quote that's been deleted. This results in `Trying to get property 'quote' of non-object`, not exactly the error from the initial sentry issue. 

I've made sure that when quotes are deleted also the likes are deleted, and I've verified there are currently no likes in the database on quotes that no longer exist.

There is no user ID in the sentry event, so I'm not sure if there's anything else I can do. :(
