### ISSUE TITLE
FALSE ACHIEVEMENT?!?!?!?!

### ISSUE THREAD

**Issue by Harladus** [saproto/saproto#1010]
Dear HYTTIOAOA committee,

Because I cannot disclose any personal information, here goes my best description of this person. I have discussed the issue below with one of your members and we both felt the need to point this out to you. In other words, this is a very serious issue.

There is this certain person within the association, this person has been around quite some time and he/she obtained the "Big Spender" Achievement. HOWEVER, this person achieved it when the maximum amount to be withdrawn was lower than 250 euros. Since the achievement was updated and now specifically states the maximum amount is 250 euros, this person does not deserve this achievement anymore. My question is if you could identify the imposter and either change the achievement or take it away from the false owner. 

Thank you for your consideration.

**Comment by xadya** [comment]
I very much agree with this.

**Comment by jonathanjuursema** [comment]
Hey @Harladus! 👋 Have you considered that it would be possible that although this imposter person 🕵️‍♂️ might not have been **charged** 💰 €250 in a month due to the withdrawal limit they might still have spent 💸 the money, only to pay it off over the next few months? 📅 Either way, you may disclose the name of this imposter to me via a the best secure and private channel you can come up with, and I will PERSONALLY investigate this most serious of serious bug. 🐛
