### ISSUE TITLE
Person has signed an NDA button doesn't seem to work

### ISSUE THREAD

**Issue by sainety** [saproto/saproto#1013]
Heyo, 

It seems like clicking the button "User did not sign an NDA" for a user on their admin page should change this users status to :"User signed an NDA". However, this isn't working currently. It this a broken button situation, or am I just stupid and do I find the option to show an NDA has been signed by a user somewhere else? 

Sanne

**Comment by xadya** [comment]
AFAIK this button should be pressable in the user administration. Please try it there or send me a message about whom this regards :)

**Comment by sainety** [comment]
That's what I've tried! It doesn't seem to work. It doesn't work for the mulitple people that have signed an NDA in the past week, so it seems to be a general problem, but I can still send you a message about whom it concerns. It also isn't just me for who the button doesn't seem to work, we've tried yesterday and other board members seem to have the same issue.

**Comment by jonathanjuursema** [comment]
This is for now intentional. When the NDA tracking in the site was made the idea was that only sysadmins could toggle the NDA status (for example so board can't toggle their own NDA status) since the HYTTIOAOAc was made responsible for the NDA's (and not the board). Sysadmins can click the button. But for board the button looks clickable, so I see the confusion and agree this is confusing.

Should we discuss next meeting whether board should also be able to toggle NDA status?

**Comment by thijsdortmann** [comment]
Discussed in the meeting, fixed in 566de7e5afc902ec9e7d9b63d44d4a478981b11f and thus done.
