### ISSUE TITLE
Clearer information on how to cancel a membership

### ISSUE THREAD

**Issue by hanotonah** [saproto/saproto#1081]
Hello hello,

From some of the emails I get from people who want to cancel their Proto membership, it became clear that there's no clear information on the website as to what the protocol is for this. 
Is it maybe an idea to add a small piece of text somewhere on a profile's dashboard with more information about this? Or is this intentionally not mentioned?

My suggestion would be the following:
Add a italic piece of text to the bottom of the "Your membership" block on your dashboard, which says:
_Do you want to cancel your membership? Send an email to secretary@proto.utwente.nl. Please note that memberships are only cancelled in August._

Let me know what you think :D

**Comment by jonathanjuursema** [comment]
Technicality: memberships can be canceled any time, there is just no restitution for the remainder of the fee.

Also, might want to look into the option to set an end date for membership again. Maybe including the option to cancel yourself?

**Comment by hanotonah** [comment]
Perhaps the message could be changed to: 
_Do you want to cancel your membership? Send an email to secretary@proto.utwente.nl. Please note that memberships are only cancelled in August, since you have already paid your fee for this year._

About setting an end date: would this not cause only more confusion towards the end of the year? Then there will be both people sending emails they want to cancel their membership, and others who maybe to prolong their membership after all. 

Including the option to cancel yourself might be an idea!

**Comment by jonathanjuursema** [comment]
@hanotonah regarding cancelling yourself, could you discuss this with the board and let us know if you want this or not?

And regarding the flexible end date, the use case I can think is "I want to stay member untill x, and don't receive mails after that". But here also a decision from the board would be great. <3

**Comment by hanotonah** [comment]
We spoke about it today, and these are the conclusions:

- In any way it would be nice to inform members better about cancelling their membership, right now it is too vague.
- The board thinks that giving members the option to set a date for ending their membership is not a good idea. Next to maybe receiving even more mails, it could pose problems when this person still has upcoming withdrawals. This could be fixed by always having the end date be at the end of the year, but the next option has our preference:
- Adding a button on your dashboard where people can click on if they want to cancel their membership. On the background, this will put them on a list accessible to the board (or at least secretary) that can at least be accessed at the end of the year. The member will (automatically) receive a standard email with information about cancellation (it has been noted that you want to cancel your membership, it will be cancelled at the end of the year since you already paid, you can unsubscribe from mailinglists (except GMM and other really important stuff, withdrawals)). This kinda automates the process that is already in place, namely the secretary who sends the same email every time someone want to cancel their membership.

The exact implementation is of course up to you guys, but this is what we could think of :)

If you have any questions, don't hesitate to send me a message :)

**Comment by xadya** [comment]
@point 2 - We have the right to store data even if they are not a member anymore to ensure fulfilling the financial contract.

Third point sounds good though :)

**Comment by jonathanjuursema** [comment]
I'm not so sure about the third point. This would make the system cumbersome (why, if we're automating the whole process of requesting membership termination, would we still require the manual button press to do this at the end of the year, which could be forgotten) and probably as confusing to the end user (now, instead, we have to make abundantly clear that they're not yet no longer a member, but they've been placed on a list that means that they're probably no longer a member at the end of the year, but please check back to make sure because it's still a manual process). I think that if we opt to have something do-it-yourself on the website, it really should be do-it-yourself, and if some manual intervention is required keep it completely manual.

We could also try to automate the checks you guys do when you terminate a membership? We can easily check if there are open orderlines or activity participations, redirect users to Mollie if they want to pay that balance immedeately, or make it possible to terminate your membership with open orderlines but prevent deleting your account with open orderlines (because at this moment, we already have non-members with open orderlines around times such as the gala).

**Comment by hanotonah** [comment]
Hey,
Sorry it took so long to answer. I'll try to write a summary of the board's opinion.

We don't agree that having one part where the user needs to do something manually would make the system cumbersome. I think having a button with information of the termination of membership process is less confusion than not giving information at all, which is the case now.

However, if it's okay by you to automate the whole process while making sure that no onderlines are left unpaid, they are not signed up for any activities or any other business is left unattended, that's cool by us! Do your awesome hackedy hack skills :) 

I do think this would require the user who wants to unsubscribe to at least be given information on the process and double checking whether (s)he really wants to go. If you would like input on this, hit me up!
