### ISSUE TITLE
Counting People at Drinks

### ISSUE THREAD

**Issue by PetervanderBurgt** [saproto/saproto#1094]
Dear HYT,

During last GMM a solution for counting people at drinks came up.
We discussed it further in the TIPCie meeting, and would hereby like to ask for it to be implemented.
Would it be possible to count the unique persons buying a Tipcie product (products in the tipcie store) and display it for example in the tipcie order overview?
Thanks in advance!

**Comment by thijsdortmann** [comment]
We can definitely look into implementing this :) Have you kept in mind that not all people might be paying with a personal card, but some might be using the PIN / cash option?

**Comment by Jessseee** [comment]
We have discussed this during last weeks meeting and the result was that we could possibly count the number of individuals that pay using their Proto registered card. 

But this might not be a very accurate representation of the number of people present at the drink. Both because people paying with pin will not be counted and people tend to buy drinks for other people.

If this is accurate enough for you we could look into implementing this.

**Comment by Jessseee** [comment]
I do not think this is a viable project and for that reason will close this issue.
