### ISSUE TITLE
Saving membership contracts on the Proto site

### ISSUE THREAD

**Issue by MaartjeHuveneers** [saproto/saproto#1152]
For now, we cannot get new members to sign the membership contract. I've already talked to Ellis/Xadya about this, and for now, we'll do it through mail.

However, also for signing up members during the Kick-In, I think it'd be much better to have some sort of system on the site for signing the contract. How I'd see it:

- Add another step to the checklist of becoming a member, which involves signing a contract (both the downloading part and the uploading part, described below)
- The (not-yet-)member can download their own contract on their computer (like the board can do now in their user profile)
- The member signs their contract on their computer
- The site gives an option to upload the signed contract to the Proto site
- The Proto site gives a verification to the user (and in their user profile, so the board can also see the contract has been uploaded) and stores the contract
- A board members checks if the contract has been filled in correctly and helps them out further with the registration process.

I'm curious about the possibilities! Let me know if you need to know more :)

**Comment by Jessseee** [comment]
We prefer not to make a feature that will only be used during the corona crisis. Instead we want to propose to stop taking signatures at all. We are convinced that signatures could be easily replaced with a check mark to confirm, without legal or technical drawbacks. The new memberships will have to be confirmed by the board still.

**Comment by xadya** [comment]
I do not agree with the abovementioned, since a contract is signed and this should be signed by a unique and identifiable sign (handtekening). Therefore either the sign should be scanned, or made in a drawing field. https://www.eur.nl/sites/corporate/files/2015_augustus_De_rechtsgeldige_ondertekening.pdf If you have other info where is stated that a checkmark is sufficient, i am happy to hear.

**Comment by jonathanjuursema** [comment]
Okay, I've Googled for ["electronic signature checkbox"](https://www.google.com/search?q=elektronische+handtekening+vinkje) and the first three hits show me this (in Dutch unfortunately):

"Zo kan een mondeling “akkoord” dus een rechtsgeldige overeenkomst tot stand brengen. Maar ook het zetten van een vinkje of het akkoord gaan per mail kan tot een juridisch bindende overeenkomst leiden."

"Dit geldt ook bij toestemming onder de privacywet. De regels voor zulke toestemming zijn strenger dan voor ‘gewoon’ een rechtshandeling: de privacywet eist “vrije, specifieke en op informatie berustende” toestemming. Maar ook hier geldt niet dat die toestemming schriftelijk moet zijn gegeven of dat deze pas gegeven is als men een krabbel op papier heeft geproduceerd. Wederom, die handtekening is handig als bewijs, maar dat is het dan."

"Een wilsverklaring kan daarbij allerlei vormen hebben: een mondeling akkoord, een gestuurde email of een geplaatst vinkje in een webshop. De overeenkomst is daarmee feitelijk tot stand gekomen."

Given the fact that I opened my bank account, engaged in all sorts of subscriptions, and make regular purchases without providing a physical signature, I would argue that a checkbox would be ok. :)

**Comment by xadya** [comment]
There is a difference though between a fixed contract (ie, you pay amount x on day y or you pay x per year) and a proto contract. At Proto people pay the member fee + their own expenses. I think it is arguable that the contract is therefore semi-important because people can spend up to 3k a year on Proto if they would try and this might not be known beforehand. Hence the more important the contract the more we must try to confirm the identity of the subject. Everyone and their mom could make an account and fill in other information, so we need to think about that. 

Het vaststellen van de identiteit van de ondertekenaar is een heel belangrijk element om de betrouwbaarheid van de elektronische handtekening vast te stellen. Hoe belangrijker het contract, hoe zekerder je moet weten wie de elektronische handtekening heeft gezet. 

Voor de rechtsgeldigheid van een over­eenkomst is het lang niet altijd nodig om een digitale handtekening onder het document te plaatsen. Volgens de wet is een overeenkomst immers in beginsel ‘vormvrij’. Dit houdt in dat partijen op iedere gewenste manier een overeenkomst kunnen sluiten, zelfs via gebarentaal of stilzwijgend. Ook een e­mail met daarin een omschrijving van de overeenkomst en een ‘akkoord’ voor de aanvaarding van de overeenkomst is volgens de wet rechtsgeldig, evenals een vinkje bij ‘akkoord’ in een webformulier.Op het moment dat een van beide partijen onder de overeenkomst uit wil, kunnen echter problemen ontstaan. Het is dan bijvoorbeeld lastig om te bewijzen dat een koper een e­mail met daarin ‘akkoord’ daadwerkelijkheeft verstuurd, of daadwerkelijk het vinkjeheeft geplaatst.Een elektronische handtekening kan dan  uitkomst bieden. De ontvanger van de  handtekening kan hiermee bewijzen dat  een bericht of akkoord van de verzender afkomstig is. De bewijskracht hangt echter af van de manier waarop de elektronische handtekening is geplaatst

**Comment by Jessseee** [comment]
Conclusion after some more deliberation, we decided to implement a digital signature field in the membership form.

**Comment by MaartjeHuveneers** [comment]
And how will the membership form then be shown to the new member? + Will the signed contracts then be saved on the site?

**Comment by Jessseee** [comment]
This will be part of the become a member flow and of course the signature will be saved in our database.

**Comment by MaartjeHuveneers** [comment]
Sounds good!
