### ISSUE TITLE
Ordering folders on the Wiki

### ISSUE THREAD

**Issue by MaartjeHuveneers** [saproto/saproto#1160]
Right now, the pages on the Wiki are ordered on the date of adding them. Is there a way to manually re-order the pages?

For example, here: https://wiki.proto.utwente.nl/education/study/start it would make more sense to order the folders like: Y1, Y2, I-Tech, Other than the order it is in now.

Is there some way for us to manually do this or for you guys or does something new need to be implemented to do this (or is it just basically impossible)?

**Comment by jonathanjuursema** [comment]
@MaartjeHuveneers I don't think there's a simple way to order other than alphabetically (you can reverse the order though I believe).

What we could do in this specific case is rename the pages (not the titles, just the URL's) so that when sorted alphabetically, they will be in the right order.

So renaming year1 and year2 to 1styear and 2ndyear would do the trick. Would that help?

**Comment by MaartjeHuveneers** [comment]
I've now changed the URL in Other studies to z_other, which does a similar trick. However, if you change the URL, everything that is stored within that subcategory, needs to be moved as well. So if you'd like to change the order, so that Y1 is on top, you'd have to change Year 1 to a new URL, but also all modules and also all subjects within those modules.
So it's quite some work to do :p 
But I also understand that there's not really a way to fix it, so sad.

**Comment by jonathanjuursema** [comment]
Renaming an entire category is something that I can do for you. :)

**Comment by MaartjeHuveneers** [comment]
Oh nice! Next time I'll make sure to ask you :)

**Comment by jonathanjuursema** [comment]
@MaartjeHuveneers so at this point there's nothing that we need to do? If so, can you close this below? 👇
