### ISSUE TITLE
Previous boards page index

### ISSUE THREAD

**Issue by hanotonah** [saproto/saproto#1196]
To be able to easily navigate between previous boards, I think it would be nice to have an index or something with hyperlinks to all the boards, so you don't have to scroll all the way down for the most recent boards :)

I talked to Jesse and he was enthusiastic about making it hihi <3

**Comment by Vlieking** [comment]
Hi, I'm gonna hijack this thread for a bit, since now that we're discussing this anyway, it is (in my opinions) more logical for the old boards page to be indexed with the most previous board at the top and then work its way downwards (Im honestly not saying that because I want to be at the top of the page, most associations have this order as you'll more often want to see the more previous boards if you have a reason to be on the page) 

Kind regards,

**Comment by xadya** [comment]
Abacus' solution is pretty neat too: https://www.abacus.utwente.nl/nl/board/53.html

**Comment by Jessseee** [comment]
I have added an index dropdown. You can check it out on the [old board page](https://www.proto.utwente.nl/page/oldfarts).
