### ISSUE TITLE
RFID linking thru existing link

### ISSUE THREAD

**Issue by renskruining** [saproto/saproto#130]
Using a previously linked RFID card, link new cards. Preferable, it is (:

**Comment by jonathanjuursema** [comment]
When I was about to get started on this I realized it is a small security risk. If there is a malicious user that borrows someone's card they can easily link another card to that account and silently use that someone's account until that someone figures at there was an extra card added. This is not currently the case, where each added card can only be done by someone who knows the actual account credentials and chooses to connect a card very explicitly. 

@thijsdortmann @DennisVinke what are your opinions?

**Comment by jonathanjuursema** [comment]
No opinions? :(

**Comment by thijsdortmann** [comment]
I think this issue originated back when everybody needed to link their new card because of the new reader, and was supposed to be a feature to use the old reader as a means of linking a card using the new reader. These days, almost everybody has their card linked up, so I don't think this is an issue anymore. Considering the security risks @jonathanjuursema is stating I think we should close this one.
