### ISSUE TITLE
Association/For Members categories indistinguishable 

### ISSUE THREAD

**Issue by margotr** [saproto/saproto#301]
It is now unclear what the differce is between the two categories. E. G. The quotecorner is under 'association' even though it's especially 'for members'. Please ask the board to reconsider the categories!

**Comment by margotr** [comment]
ce is between the two categories. E. G. The quotecorner is under 'association'  even though it's especially 'for members'. Please ask the board to reconsider the categories!

**Comment by jonathanjuursema** [comment]
The problem is that some menu's are hardcoded and some are dynamically adjustable by the board. But I do agree it is inconvenient. We could keep some functions (like the quote corner) in the dynamically adjustable menu's, as long as the board don't make them vanish and/or can find [their URL](https://github.com/saproto/saproto/blob/master/app/Http/Routes/primary.php).

Basically we can remove the static carreer and association menu's, as long as the board manages them via the menu functionality. @DennisVinke and @saproto/website-developers, what do you think?

**Comment by jonathanjuursema** [comment]
@DennisVinke @saproto/website-developers can I get feedback on this? It's quite a large change in the menu structure so I'd like to have some feedback before I go through with this.

**Comment by thijsdortmann** [comment]
In that case we should probably keep a list of routes that are handy to have in the menu, or even better, get the routes that can be accessed by members and regular visitors and generate a list of those to select from :)

**Comment by jonathanjuursema** [comment]
That sounds cool!

**Comment by jonathanjuursema** [comment]
@DennisVinke can you give some board feedback on this? It's the only thing we're waiting for.

**Comment by DennisVinke** [comment]
Never got feedback for the career page, but the board would like a way to order the menu layout. If this is done, I would appreciate a feature were the board can see all possible routes in case someone deletes a link by accident.
