### ISSUE TITLE
Adding a banner for 3 types of activities

### ISSUE THREAD

**Issue by xadya** [saproto/saproto#360]
1 activity is free and should have a color (green/blue?)
1 is paid (orange/red?)
1 is deposit for sponsored activities (other color)

color should be where the price is now.

Jonathan knows more and i don't really know how to explain better.

**Comment by jonathanjuursema** [comment]
I changed the concept slightly away from "deposit" and more towards "no show fee", because it seemed more logical both in the application flow and for display on the event page. This also allows to have a now-show-fee that is different from the activity price.

With this commit also comes a safeguard: both the participation fee and no-show-fee cannot be changed upwards as soon as there's participants to the activity. Both fees can be reduced though.
