### ISSUE TITLE
Add option for all-day events to events

### ISSUE THREAD

**Issue by DennisVinke** [saproto/saproto#409]
The Proto iCal calendar has a bug where it shows an event for the whole day if an event takes op multiple days.

**Comment by DennisVinke** [comment]
Abel also come with the suggestion to make certain events toggle-able so they do not take up multiple days in his agenda.

**Comment by regnerus** [comment]
It happens when events are not listed as "whole day events" but instead have a start and ending time, such as the UTChallenge. It kind of messes up my whole calendar in such a way that I have to disable the Proto Calendar.

<img width="1046" alt="screen shot 2017-04-05 at 16 12 27" src="https://cloud.githubusercontent.com/assets/285450/24709638/d8adeb48-1a1a-11e7-8e5e-0aff9da0aef9.png">

**Comment by jonathanjuursema** [comment]
I pushed something that should fix it, but i can't test since I don't have access to any apple calendar stuff. Can you let me know if this worked?

**Comment by regnerus** [comment]
I think it is fixed, the UTChallenge disappeared from the activities but the curiously "week long" study night for documentary practice (https://www.proto.utwente.nl/events/706) now appears as an all-day event.

**Comment by regnerus** [comment]
Actually just noticed that it doesn't work correctly. The study night event I mentioned in the comment above is from Tuesday 11 April 2017, 18:00 till Tuesday 18 April 2017, 23:59 but my calendar says its an event from 11 untill 17.

**Comment by thijsdortmann** [comment]
Make it possible for board members to create all-day events.

**Comment by jonathanjuursema** [comment]
I'll close this feature proposal since there hasn't been any expressed interest as per the [guidelines](https://wiki.proto.utwente.nl/ict/issues#special_notes_for_feature_proposals).
