### ISSUE TITLE
Online gossipbox

### ISSUE THREAD

**Issue by renskruining** [saproto/saproto#526]
Dear,

There used to be an online gossipbox once. We would love to see the return of it. It worked as follows:
Someone went to a page with a text-field and inserted their gossip. This was then sent by mail to the senatus viridi. 

A very simple concept, I must admit, but can therefore also probably be implemented easily.

As this would be a more permanent page, I request this instead of making a small one on, for example, my own domain.

Thank you very much!

**Comment by jonathanjuursema** [comment]
To keep the concept more generic (because there are also other usecases being discussed) I added an option for the board to enable for committees that they can receive anonymous e-mail. If this is enabled, a link to a form is shown on the committees page. Please ask the board to enable it for your committee. :)

**Comment by renskruining** [comment]
👌🏻

Kind regards/vriendelijke groet,

*Rens Kruining*
+31 6 46 51 86 73

On Fri, Sep 29, 2017 at 2:36 PM, Jonathan Juursema <notifications@github.com
