### ISSUE TITLE
design of "wiki" on saproto.nl

### ISSUE THREAD

**Issue by renskruining** [saproto/saproto#535]
Dear,

https://www.proto.utwente.nl/page/gmm seems to break with a high number of links upon different sizes of screens (mobile, laptop vs 1920x1080 or wider)

I would like to inquire you to improve this layout, preferably even a mobile-layout as default. 
(all links listed below each other in one column.)

thank you

**Comment by thijsdortmann** [comment]
This part of the wiki will be retired as soon as the board has moved all the content over to our proper wiki at wiki.proto.utwente.nl :)

**Comment by renskruining** [comment]
May we then also implement wiki.saproto.nl(as a forwarding link) and a link
from the main website?
The forwarding link is as the website itself is also reachable as saproto.nl
(and should remain so)

Kind regards/vriendelijke groet,

*Rens Kruining*
+31 6 46 51 86 73

**Comment by jonathanjuursema** [comment]
There will be a link to the wiki on relevant parts of the website.

We're not going to have a wiki.saproto.nl because there are nearly no links to that website anywhere and we don't use saproto.nl anymore. We keep the saproto.nl domain though because there still exist links on the interwebs to pages on the old website, and to prevent pranksters from getting the domain. :)
