### ISSUE TITLE
Proto e-mail address on profile page

### ISSUE THREAD

**Issue by renskruining** [saproto/saproto#579]
Dear,

At the moment proto e-mail addresses exist, but there is no way to show them on your profile page (instead of your actual email address).
This renders them almost useless, but it would also improve on privacy if the real email address was hidden.

I hope this can be changed.

**Comment by jonathanjuursema** [comment]
This is technically no problem. However, since it changes the way information about other members is available to other members, I would first like to know if a large group of people (including the @saproto/board) is in favor of this change.

**Comment by Habenga** [comment]
Making this an option would be nice.

**Comment by sbkoomen** [comment]
We like this change, as well as adding in the option to hide your email address completely. That way, Proto members could either make their email address publicly available through their Proto alias or hide it from their profile completely.

**Comment by jonathanjuursema** [comment]
Because there were no objections but definitely benefits your profile page now shows your Proto e-mail if available. We did not add an option to hide your e-mail because of pre-existing [considerations](https://wiki.proto.utwente.nl/ict/privacy/details#additional_pii_for_members) that @sbkoomen was not yet aware of. :)
