### ISSUE TITLE
Opt-in event reminder mails

### ISSUE THREAD

**Issue by renskruining** [saproto/saproto#586]
Dear, 

Would it be possible to automate optional mails, that remind of a event that has opened up for sign-up, and a reminder (the night beforehand) for an event that the user has signed up? 

This would be awesome in my opinion!

**Comment by jonathanjuursema** [comment]
@renskruining I see not many upvotes on this issue, and combined with the fact that the imported calendar can now also show if you're attending or helping, makes me wonder if this feature request is not superfluous. Do you think it's still worthwile?

**Comment by renskruining** [comment]
@jonathanjuursema Hi!
I don't see many either, but I think that is mostly an issue of using github (another place people need to create an account and all that).
However, I think it is still worthwhile since it is different from the "updated" calendar _(I don't see any changes, though)_ as the calendar does not serve as reminders. The mail reminder should be opt-in to not be obtrusive to people that don't want it, but I think it to be something less than normal for an organisation (seeing the hairdresser doing it as well).

The calendar, I only look at to see when an event is: in week or day overview, and to see the location in the same view. The link and description things I only see when opening the item in my calendar application/website. This I don't do very often (close to never).
An email would work for me, and other busy minds, as it would "interrupt" my flow and remind me of what is about the come/what I signed up for. 

Maybe the function of promoting sign-ups can be deemed as unnecessary by the saproto-board, but I think the reminder in case you signed up can ~~_(and should)_~~ be used by many.

**Comment by jonathanjuursema** [comment]
> I don't see many either, but I think that is mostly an issue of using github (another place people need to create an account and all that).

We see it as the [responsibility of requesters to actively ask around](https://wiki.proto.utwente.nl/ict/issues#special_notes_for_feature_proposals) if other other people are interested. There is indeed a barrier for upvoting, but on the other side we don't require a large amount of upvotes before consideration (the wiki currently says 20, but in practice it's more like 5/10).

> However, I think it is still worthwhile since it is different from the "updated" calendar (I don't see any changes, though) as the calendar does not serve as reminders. The mail reminder should be opt-in to not be obtrusive to people that don't want it, but I think it to be something less than normal for an organisation (seeing the hairdresser doing it as well).
>
> The calendar, I only look at to see when an event is: in week or day overview, and to see the location in the same view. The link and description things I only see when opening the item in my calendar application/website. This I don't do very often (close to never).
> An email would work for me, and other busy minds, as it would "interrupt" my flow and remind me of what is about the come/what I signed up for.

We only promoted it on Facebook now, so you may have missed it (we might consider a news item on the homepage), but you'll need to add the calendar to your calendar application again in order to receive personalized updates (there is now a personal calendar URL on the [calendar page](https://www.proto.utwente.nl/events) where previously it was only a generic one).

> Maybe the function of promoting sign-ups can be deemed as unnecessary by the saproto-board, but I think the reminder in case you signed up can (and should) be used by many.

Alternatively, instead of sending yet another e-mail (we are cautious with sending too many automated e-mails) there may be a functionality that it more appropriate. I believe we can change the calendar URL (the one you import in your own calendar application) to set 'alarms' for activities that you are signed up to. On Android, these result in a system notification a set time before an event starts. Maybe that is more appropriate?

**Comment by renskruining** [comment]
Ah, yes, the all time favorite communication medium facebook. 

That sounds like a possible and appropriate solution. The calendar with notifications would work for me.

**Comment by jonathanjuursema** [comment]
Unfortunately Google Calendar completely ignores any RFC compliant notifications passed via the calendar. This is known behavior if I am to believe some searches. It should work in other clients though.
