### ISSUE TITLE
Soundboard timeout/limit

### ISSUE THREAD

**Issue by renskruining** [saproto/saproto#597]
Dear,

sometimes the soundboard is abused, so I would love a limit on the use of the soundboard, so people don't spam it.

Thank you very much

**Comment by jonathanjuursema** [comment]
If any temporary admin abuses the soundboard, their access can be revoked by the board. And since they're the boss, we're not going to build something that board members can use to kick themselves. ;)

If you feel the soundboard is abused please let the board know so they can kick the tempadmin. If you feel the board is abusing their privileges beyond what is allowed according to the policy, you can e-mail us. Otherwise please contact the board or bring it up during a GMM. :)

**Comment by renskruining** [comment]
It is the Have You Tried Turning It Off And On Again committee that was
abusing it today.

With kind regards,
Rens

**Comment by jonathanjuursema** [comment]
In that cast it's the other way around, if one of us is abusing, please contact the board! You can also send me a private message if you feel I'll handle it fairly.
