### ISSUE TITLE
Personalised Event notifications request

### ISSUE THREAD

**Issue by Habenga** [saproto/saproto#648]
Would it possible to receive a notification (via email) when an event of your preference is organised?
This could also be done with a popup or the welcome banner op the site.

So instead of just Weekly Newsletter, have categories such as study-nights, drinks, games, food, big event, etc. and receive only info about those every week.

Please also add a check to avoid double notification options. (so remove event from newsletter if personal notification set)

This could be event category based and/or maybe keyword based.

**Comment by jonathanjuursema** [comment]
This would be possible, but a lot of work. As an alternative, might I suggest adding the full Proto calendar to Google Calendar (if you configured it to only sync relevant events than you can also just add the non-personalized calendar URL). You don't have to show the calendar in your calendar overview. Then, you can head over to the calendar settings and for that full Proto calendar enable to option to be notified, by e-mail, about new events in that calendar. That would mean you receive an e-mail whenever an event is created.

The only downside is that you won't be able to specify categories. However, I think the category system may be flawed because there are not set-in-stone categories and there's only a small subset of activities that can be neatly ordered and boxed in a category. Alternatively, we could use organizing committee instead of activity type.

However, would my first suggestion already be what you're looking for?

**Comment by jonathanjuursema** [comment]
Okay, that's clear. Let's see if there are other people interested in this feature!

**Comment by jonathanjuursema** [comment]
Due to limited upvotes we've decided during our last meeting to close this issue for now.

However, we do plan on considering a similar notification system as soon as we have a way to consistently deliver messages to people's phone, so something similar might happen in the future!
