### ISSUE TITLE
Notification/information channel settings

### ISSUE THREAD

**Issue by Habenga** [saproto/saproto#649]
Would it be possible to set up how you want to be notified about events and information about proto?

So email, banner, pop-up, corner bubble, notification icon, slack channel, (facebook?????) ....
Preferably per 'mail list/channel'

(Of course, the board should still be able to send a general announcement mail due to formal communication stuff)

**Comment by jonathanjuursema** [comment]
This sounds a bit like the way Facebook does their notifications, where you can select if you want them via push message or e-mail, per type of notification? This could be done, but I think it would be a lot of work for very little benefit. A lot of the e-mails we send you really want (or need) as an e-mail (newsletter, withdrawal notification, association announcements) so that only leaves some small stuff that, from an association point of view, I would also prefer to e-mail (help needed with activity or activity updates for example). Notifications are to easily dismissed or read over.

**Comment by Habenga** [comment]
Yes, Facebook actually does this very well. (irrespective of one opinion on the content of said notifications)
This would indeed be most useful for events and emails related to them (event updates).

Newsletters are good but tend to go unread and is primarily used for events, that is why I suggested more targeted newsletter/notification. (And then when its targeted the can be moved to smaller bite-size chunks that can be moved around)(front-page banner usage on the site is just a logical next idea)
I personally love email but many younger people hate it and want notifications and Whats-apps and what not. The point is that you point about notifications seems to be sort of the other way round for younger people. A list of old notifications would indeed be necessary to have a sort of archive (like Facebook does)

**Comment by jonathanjuursema** [comment]
I think I see your point (though I do not necessarily agree with it), but I'm not yet sure how we would actually implement your proposal.

For instance, the only (technologically) feasible communications channels right now are e-mail, SMS and push notifications in the hopefully-soon-to-be-released app. SMS is very expensive when deployed at large scale, and the app is not yet ready (side note, the app will probably already receive some kind of push notification for new activities and such).

I'm also curious to the types of notifications you would like via another channel than e-mail.

**Comment by jonathanjuursema** [comment]
We have discussed this proposal during our meeting, and decided to reject it for now since we don't have any viable communication channels outside of e-mail. When we launch the app we will look at something similar to this, incorporating push notifications.
