### ISSUE TITLE
Search for Protube Hits

### ISSUE THREAD

**Issue by Harladus** [saproto/saproto#684]
Dear HYTTIOAOA,

Wouldn't it be awesome to see how many times your favorite song was added to the protube and find like minded people? And I am not only talking about the ProTube hits, but a feature with which you can search for a particular song and see how many times it has been played, to give the "non-ProTube hits" some credit as well.

Thank you for taking my proposal in consideration.

**Comment by jonathanjuursema** [comment]
I'm not sure if we can show the "like minded people" due to privacy concerns (maybe @xadya has an opinion about this) but we can definately do more with the ProTube history (we have a lot of it!). Drop your suggestions here and [get people to vote for this idea](https://wiki.proto.utwente.nl/ict/issues#special_notes_for_feature_proposals), and we'll see what we can do. :)

**Comment by xadya** [comment]
Maybe make it optional (and opt-in), can imagine people would really like to see people who like the same music as they do.

**Comment by DennisVinke** [comment]
I think it is better to keep this as an opt-out function. We already have a do not track Protube option on the site and this could also be used to, or another button can be added for this future. As long as all references to the user that does not want to show up are removed retroactively it is also conform for the new GDPR. 

I do not see this function work otherwise because people can't be bothered to click on the opt-in button.

**Comment by jonathanjuursema** [comment]
We currently have no time for this so we are not able to do something with this proposal right now. We do think it's worth pursuing when we have time though, so we'll assign it our newly invented label: "Good idea! Might be implemented later." (when we have more time and less other issues).
