### ISSUE TITLE
Remove links to non-member profiles from various admin interfaces.

### ISSUE THREAD

**Issue by thijsdortmann** [saproto/saproto#696]
Non-members currently don't have a Proto username. The URL for the profile consists of /user/proto-username, so visiting this for non-members is not possible.

**Comment by jonathanjuursema** [comment]
As far as I recall this was intentional. Non-members do not partake in the association so there is no need to reveal any information about them to anyone but the board. I was pretty sure (although I can't seem to find the check in the code now I look for it) that this was also not possible in the old URL system, where one would get a 404 or 403 when trying to access the profile of a non-member. Similarly, [non-members can also not visit the profile of members](https://github.com/saproto/saproto/blob/master/routes/web.php#L108).

As far as I'm concerned, if I'm wrong about it being impossible to view non-member's profiles in the past, this is actually a bug fix. :)

**Comment by thijsdortmann** [comment]
The reason for this issue is the fact that in some places (user admin and committee pages with non-member committee members, and possibly other places) links to profile pages of non-members exist. These used to link to /user/user-id, and are now linking to /user/, which just sends the logged-in user to their own profile.

I agree that there is no use for profile pages of non-members. Maybe we should instead remove the links to non-member profile pages :)

**Comment by jonathanjuursema** [comment]
Sounds like a plan!
