### ISSUE TITLE
Replace poster request text with a Design Request form 

### ISSUE THREAD

**Issue by daniepyromanie** [saproto/saproto#718]
This will make it harder for people requesting a design to forget information or to forget using the request template.
However, because some people have special requests (like the Dynamic Lighting in the SmartXp request), it should be possible to fill in additional info & add attachments (like images). That part of the form should not be required to be filled in, the rest should. Once the form is filled in and sent, this information will be sent to the GraphiCie in a nice template email. 

Maybe the contact person has to fill in both a name and an email address/phone number so they can be contacted.

This can replace the list of things that need to be filled in, the rest should stay (maybe slightly edited) as it gives more info on how the committee handles requests. 

Thanks <3

**Comment by jonathanjuursema** [comment]
I've updated [this wiki information page](http://wiki.proto.utwente.nl/members/active/posters) with a form. That goes straight to the inbox of the GraphiCie. I locked it down for editing to prevent e-mails from being redirected or other stuff, so if you need to change it let us know as a comment on this issue! (Don't forget to re-open it as well.)

The page on the website will probably be removed soon, since we are migrating all static info pages away from the site and to the wiki. You can discuss with the board if you need a link to the poster form in the menu, they can fix that for you. :)
