### ISSUE TITLE
OmNomCom max per day/week/month

### ISSUE THREAD

**Issue by monjainox** [saproto/saproto#732]
Hey there, 

I have some troubles with my Proto bill every month, and I am guessing I am not the only one. This idea I had might save my wallet, and many others. 
I was thinking...
What if you could add some 'maximum spending' filters to your proto profile. In my head it looked something like this:

![whatsapp image 2018-05-22 at 11 51 44](https://user-images.githubusercontent.com/39517901/40355625-353da534-5db7-11e8-8427-f8153b74c362.jpeg)

You would be able to add multiple filters, select day week or month with a drop-down menu and then type the amount you want to be your max. 
Then, when you pay for something in the omnomcom you get a message saying thank you (as it is now) but also how much you have spent on that day/week/month out of your max (depending on what filters you activated).
For example, I have my day max on 3.00 and I pay for my foods I get to see: Daily maximum: 1.50/3.00. 
When you spent more then your max the message could be something like: hey! You have already spent your maximum amount! Daily maximum: 4.50/3.00.

I hope you like this idea.

**Comment by jonathanjuursema** [comment]
This is possible (and I believe you are not the first one to propose it), but there are some challenges to which I do not yet necessarily have the answers:

- People don't really read (or at the bare minimum wait for) the confirmation screen when buying stuff (I certainly don't). They just tap their unit and walk off. This would mean that you would not necessarily notice the notification and would walk away without paying.
- Showing your 'progress' is not possible in the OmNomCom since you only authenticate when buying. I'm not sure if we want to go back to a 'authenticate first' approach, although this is open for discussion.
- What happens when your limit is at €5.00, you have already spent €3.25 and buy two items of €1.00? Do you get one of the items, or does the entire order fail? And which item(s) would you get?
- Should there be an option to "ignore" your limit?

I'd like to know what you and other people think. :)

**Comment by monjainox** [comment]
Hey,

For the first point, I think people will read it if they have their limit activated. Then there is something of interest on it.
For the authenticate I am not sure what to think about this. I don't know if authenticate first would be better, in my opinion, it doesn't really matter.
I think it would be better to let the OmNomCom give you a warning saying that you went over your max, not failing the order.
If this is the case, ignore limit would not be necessary. But it is all a bit tricky if you can't show your progress on the omnomcom...
