### ISSUE TITLE
Menu bug

### ISSUE THREAD

**Issue by xadya** [saproto/saproto#741]
Something with the placement of the menu bar goes wrong sometimes. I have not found a pattern yet, but I got a screenshot
![image](https://user-images.githubusercontent.com/8876164/40729679-34596118-642d-11e8-9869-982f40521e43.png)

**Comment by thijsdortmann** [comment]
This is happening because you have too many menu items in your menubar, which causes the 'Study Association Proto' text and your menuitems to crash into each other. This results in the menu bar placement going haywire. This should only be a problem for the board and some members of the Have You Tried Turning It Off And On Again committee on specific screen resolutions.

**Comment by xadya** [comment]
Is it possible to go over the menu items maybe, @saproto/board ? Many of them only contain 1 or 2 items (dokuwiki, career, smartxp admin)

**Comment by jonathanjuursema** [comment]
We've made the menu more efficient, so this issue should be resolved. Let us know if you still encounter overflows!
