### ISSUE TITLE
One page member signup

### ISSUE THREAD

**Issue by sbkoomen** [saproto/saproto#750]
The current way of signing up members contains several steps that, especially when signing up new members during the Kick-In, take a long time to go through. Could one page be made where every piece of info is put in (so one page for name, address, number, payment information etc.) so afterwards the board members only have to print the user's membership form.

**Comment by jonathanjuursema** [comment]
There is already a [one page become a member page](https://www.proto.utwente.nl/becomeamember). This page lists all steps required for someone to become a member, with a link to the relevant places.

We have various places to enter personal data partly because of the GDPR, and implementing yet another one page sign-up would involve a lot of duplicate code that is harder to maintain. We have multiple scenario's to consider: first-time people who immedeately become members, people that already have a user account becoming a member, and people just registering a user account without becoming a member. By splitting up the sign-up steps, we now have a system that we can maintain relatively easy and that (especially given the become a member page) should be relatively straightforward.

Also, don't forget that cramming everything in one page still requires all data to be entered. Given that you still need to wait for an e-mail to arrive and that people will always make misstakes entering info, I very much doubt that yet another registration procedure is going to speed things up.

It is also the first time I've heard about time issues during the Kick-In. Perhaps, before we jump to conclusions, we should first evaluate what went wrong in the first place? Where people told they could already complete most of the registration procedure on their phone or own laptop? What was the bottleneck in the registration procedure?

**Comment by xadya** [comment]
Also the become a member page was not used last year, so it might be nice to first try it out as well.

**Comment by thijsdortmann** [comment]
Jonathan already mentions this very quickly, but the idea of the current become a member page is to it can be used by the future member without assistance of a board member.

The idea for during the Kick-In is that new members are asked to complete the steps on the page without a board member (on, for example, their phones), limiting the task the board member has to perform with them to printing the member form and actually making them a member. Data entry can be done before by the future member, and the actual steps that have to be performed by a board member should be doable in very little time.

**Comment by sbkoomen** [comment]
As far as I know the first-year students were not aware they could fill in the data to become a member beforehand, which meant we had to go through the whole process with everyone that wanted to sign up to become a member. We can try some form of mass-instruction just before the new board is approachable for the signup to smooth things out. The new board will then have to give feedback on how the signup went, so this issue can be closed for now.
