### ISSUE TITLE
Sales statistics break when calculating over long periods

### ISSUE THREAD

**Issue by MartijnVerkleij** [saproto/saproto#764]
The omnomcom is unable to retrieve sales statistics for the whole last year. When a too large period of time is selected the website returns a 500 error. This is inconvenient, as we want to be able to use it to accurately determine stock mutations of this year.

**Comment by jonathanjuursema** [comment]
Please note that there was a bug in the previous version of the function. Instead of the number of products sold, it showed the number of orderlines (which can be less if the total includes orderlines with more than one units sold). The aggregation now shows the total number of units sold and the total turnover, **NOT** the number of **orderlines**.
