### ISSUE TITLE
Picture embedding in Newsletters/Emails

### ISSUE THREAD

**Issue by PhilippeTu** [saproto/saproto#809]
I noticed that I'm missing the possibility to insert pictures in messages is send to members.
For example, in the Weekly Newsletter I wanted to include a picture of the newly redecorated Protopolis, but there wasn't an option to do so.
It'd be nice if there could be an option for this, just like there's a graph option (do we even use that? :o)

**Comment by jonathanjuursema** [comment]
Our e-mails are made up using markdown. You can embed images in markdown [like this](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#images).

You can upload images using imgur or something similar, since that functionality is not really availble on the site yet. If it happens often we can take a look into it.
