### ISSUE TITLE
Business database for Acquisition/External Affairs

### ISSUE THREAD

**Issue by JRitmeester** [saproto/saproto#833]
Each year new people come into contact with partnerships between company X and Proto. I myself run sometimes into the problem that there is no clear overview of what companies Proto is working together with at the moment, what promises have been made bilaterally (I think I used that word correctly :P) and until when certain contracts are signed for. For the efficiency of the Acquisition committee this year and years to come, it would be nice if there were a simple database containg the company names, one or more contracts (PDFs), (range of) date(s) of cooperation, contact info, address info and other notes, in order to keep track of why cooperations were succesfull, unsuccesfull, or (never) persued.

In this database, searching for companies would be done by tags (#IT, #Design, #Workshop, etc), name, and contact person.

**Comment by jonathanjuursema** [comment]
Hey @JRitmeester. It looks like you are looking for a CRM solution. If this is the case, it might be better to look into pre-built CRM solutions we can deploy for Proto. However, given the discussions that took place on a number of GMM's regarding the CRM solutions for Proto, we think it's best if you come by during a committee evening to discuss your plans. Just make sure it's not tonight since a lot of people aren't there then. :)

Based on that discussion we'll set out an action plan. For now, however, I'll close this issue.
