### ISSUE TITLE
Picture Cropping

### ISSUE THREAD

**Issue by PhilippeTu** [saproto/saproto#843]
It would be great to see a system implemented that let's us crop images directly on the Proto website. For example, if I upload a picture for a news article, if the picture is not the exact ratio it gets cropped all funky. It would be nice if a system like Facebook's banner system could be implemented. Where you upload the full image and are able drag it accross so you can position the image exactly like you want it.
If this is way too much work, could the exact sizes of the ''image boxes'' be put somewhere on the DokuWiki (or just tell me), that should work enough as well.

**Comment by jonathanjuursema** [comment]
@PhilippeTu cropping is something that we think will add little value for the work it will take to implement it. We might, though, do something about being more clear what the images will be cropped to. 

Before we do that, however, is it already enough that you can go to the image you want to replace (or another one, by going to another activity page for example) and right click > open in new tab on the image? If you do that, the size the image gets cropped to is in the end of the URL.

Remember that you need to put what's interesting in the center, since in addition to that cropping images may be cropped further depending on screen sizes.

**Comment by PhilippeTu** [comment]
That's understandable, then of course focus on other things that are more important!
I didn't know that I could already see a size, I'll let the people know ;)

**Comment by jonathanjuursema** [comment]
No problem!
