### ISSUE TITLE
Photoalbum scrolling issue

### ISSUE THREAD

**Issue by emielsteegh** [saproto/saproto#853]
If you scroll down using the arrow keys in the photo albums then you will be set back to the top instantly. and scrolling down with the arrowkeys is jittery.

Greetings,
Milan (Larry's pedestal)

**Comment by thijsdortmann** [comment]
This does not seem to be an actual bug. When viewing a photo, the up and down arrows are used to either like or remove like from a photo, while the arrow keys move to the next photo. This is indeed a bit jittery, because the whole page is reload. Is this with this knowledge something you'd still like to see changed?

**Comment by jonathanjuursema** [comment]
I'll at least fix the jitter.

**Comment by emielsteegh** [comment]
this is fine
