### ISSUE TITLE
Copy General News list for Direct Mailing

### ISSUE THREAD

**Issue by JRitmeester** [saproto/saproto#879]
Recently I have received a request of a company who wants to purchase a direct mailing, essentially a single email of advertisement for job offers, events or anything else as a sponsorship deal. I have discussed this in Slack previously with HYT. It seems the best solution to prevent people from unsubscribing from the General News list (where this would normally be sent over), that the exact same list would be duplicated to allows people to unsubscribe from _that_ list if desired. This has been discussed with the board last Monday and they agree! Yay! Would it be possible to duplicate the list?

**Comment by jonathanjuursema** [comment]
Hey @JRitmeester! I'm not sure if this is allowed because we would effectively create a new list and subscribe people to that list who didn't consent to that. Maybe @xadya has an opinion on this?

**Comment by JRitmeester** [comment]
Otherwise people would receive this over the General News list, so they'd receive it anyway. This way we give them the opportunity to unsubscribe, right?

**Comment by jonathanjuursema** [comment]
> Otherwise people would receive this over the General News list, so they'd receive it anyway. This way we give them the opportunity to unsubscribe, right?

@JRitmeester I agree with the first part but not with the second. Because depending on the way you look at it you either would have to unsubscribe from two lists where you would originally only have had to unsubscribe from one, or you would now have to unsubscribe from a list you have technically not subscribed to.

Because @xadya also believes this is against the rules, I think it's best to close this for now.
