### ISSUE TITLE
longer songs on Protube

### ISSUE THREAD

**Issue by Jessseee** [saproto/saproto#883]
I think that the max playtime of songs on Protube is too short. I understand that this is implemented to stop people from adding really long videos/songs, but there are some music genres which regularly have songs that are longer than the current max playtime. I would propose to give people with the achievement "F****** tune, mate" the ability to add songs with a longer playtime.

**Comment by xadya** [comment]
This has been proposed many (many) times in different ways. This is a choice of the board, so @saproto/board what do you think?

**Comment by jonathanjuursema** [comment]
It's also partly a technical issue. As far as I know we do or did obey a YouTube classification of short/medium/long, where the current limit is what YouTube considers "medium". Check for anything else than that classification might result in extra response time since we need to do an additional query for the exact song length. This might be outdated though. @thijsdortmann ?

**Comment by JRitmeester** [comment]
I'm a bit on the fence about it, personally, as the achievement is not something that is given under strict conditions; it's given whenever someone gives a compliment (and there is a board member that is not busy and hears the compliment). People will be asking for the achievement with a high frequency, I can imagine.

At first sight I did like the idea of allowing _some_ people to enter longer songs, but that would have to be permission-based and those people that will receive that permission are likely to be the most active protubers, therefor a _lot_ of long songs might get introduced rather than just a few on occasion.

Great concept, too rough for me personally to endorse it, but definitely worth looking into more.

**Comment by thijsdortmann** [comment]
The maximum duration of songs has been increased. This should make it possible to add most songs, while still preventing really long videos. For adding longer things, you'll have to ask someone with admin powers to add it to the queue.

**Comment by daniepyromanie** [comment]
Thanks <3
