### ISSUE TITLE
Withdrawal page, amount open to be received

### ISSUE THREAD

**Issue by maximdeleeuw** [saproto/saproto#885]
On the new page, there isn't a possibility anymore to check if the complete outstanding amount to be received, has been taking up in the next/new withdrawal. Is there a way for this to be shown again?

**Comment by jonathanjuursema** [comment]
You have already posted this issue in https://github.com/saproto/saproto/issues/829#issuecomment-435075909. Since all comments are resolved, here it is again. :)

> > On the Withdrawal page, it isn't visible how much money is still open (and to be collected in the next withdrawal)
>
> @maximdeleeuw This has been removed for performance reasons. You can see the total on the "create new withdrawal" page. If you would like to have it back, let me know. :P

Because it has already been adressed I will close this issue. If you would like to see my suggestion or have another one, please re-open this issue!
