### ISSUE TITLE
Help, the site says 10 tickets have been bought but the orderlines give only 3 purchases. 

### ISSUE THREAD

**Issue by daniepyromanie** [saproto/saproto#908]
At the image below it says that 10 tickets have been bought for the EEMCS Carnaval Unlimited Food Ticket
![image](https://user-images.githubusercontent.com/33750931/53420776-b8f28280-39dc-11e9-8cc2-1607cbcb54ad.png)

But when I click on the product i only see three purchases. 
![image](https://user-images.githubusercontent.com/33750931/53420906-f7883d00-39dc-11e9-9a0a-ee101f86dfb8.png)

Do you know what might have caused this? It also says that I have bought 2 tickets 
![image](https://user-images.githubusercontent.com/33750931/53420945-066eef80-39dd-11e9-9cd4-7862c9076712.png)
Possibly because of the previous event?

**Comment by jonathanjuursema** [comment]
This was a user error. Instead of creating a new ticket and linking it to the new event and the new product, the ticket of EEMCS Carnaval 2018 was updated with the new event and product. This means that on the product screen you will only see the three purchases of this year, but on the ticket overview you will see 10 have been sold (this is because orderlines are not linked to tickets via the product, but via the ticket_id, so by re-using the ticket of last year you also 'import' the sold tickets of then).

I have created a new ticket with the same settings, linked that ticket to the new product and event. Then I updated the old ticket to link to last year's event and product. I also updated the ticket purchases that have been made in this year to be linked to the new ticket.

Everything should work as expected now. The three people who bought a ticket for this year don't need to do anything, their ticket is valid for this year. The people who bought a ticket for last year will no longer see it under this year, but under last year's event.

All should now be as expected, please check if anything doesn't match up. Please also check last year's ticket (it should be enough to verify that last year indeed 7 tickets have been sold).
