### ISSUE TITLE
No-show-fee possibly broken?

### ISSUE THREAD

**Issue by JRitmeester** [saproto/saproto#950]
After last Wednesday's El Niño lunch lecture, 4 people ended up not showing up, and they were left at "Absent" in the participant checklist. Now that the activity is closed, as indicated by the red "Activity closed" box on top in the activity page, the no-show fee appeared to not have been added to these people's OmNomCom histories.

**Comment by jonathanjuursema** [comment]
The no-show fee is not automagically applied to people who are marked absent unfortunately, since the absence system is not always used. The no-show fee setting for activities is only visual, and the no-show fee needs to be added manually as an orderline for the absentees (do not forget to also include a note for these orderlines to make it clear to people what they paid for).
