### ISSUE TITLE
Event Tickets

### ISSUE THREAD

**Issue by jonathanjuursema** [saproto/saproto#96]
We should make a new 'even ticket' system, similar to the old one. We can import the old tickets and link tickets to 'events' in the calendar much the same way as we do with activities now.

**Comment by DennisVinke** [comment]
The 'event ticket' in itself should not be necessary because the new site has the option to limit the sign out date. We still need the function to keep track of which tickets are sold and who actually visited the event, like is done with the Lustrum and the bar scanner last year. One of the other needed functions if the ticket system is dropped, would be the ability for external members to buy a ticket for bigger events like the Gala without being a Proto member.

**Comment by jonathanjuursema** [comment]
@thijsdortmann we could add an option for 'public' activities that also non-members can sign-up for, and build some 'ticket' abstraction layer on top of activity participation. Does that seem reasonable?

@DennisVinke the only limitation in this case would be that you can't sign-up multiple times for an event. Would that be okay?
