### ISSUE TITLE
additional committee join request

### ISSUE THREAD

**Issue by Sebastiaanjai** [saproto/saproto#979]
an additional button on a committee page to show interest in a committee, ideally this button would notify the committee of the person being interested.

**Comment by Vlieking** [comment]
on behalf of the candidate board, +1. If possible, make it so that the button can be turned of/made gray when a committee does not search any more members. :)

**Comment by jonathanjuursema** [comment]
I'm not sure what the added functionality would be above the "E-mail them at" link that is already present, except for that someone who's interested wouldn't have to type "Hey I'm interested in joining your committee". Regarding the toggle, I'm afraid this would also not be as useful since people also forgot to update committee members and some committee pages haven't been updated in a while. You can also just as easily change the to include that you're looking for members, possible even showing additional info (such as what for, how many people, etc) that wouldn't be possible with a simple button!
