### ISSUE TITLE
Can't sign out of committee helper reminders after leaving committee

### ISSUE THREAD

**Issue by renskruining** [saproto/saproto#985]
Dear committee,
Thank you for helping me!

Just today I received an email as a notification for helping drafting with the iTech BBQ. I probably have subscribed to the notifications back when I was part of the Guild of Drafters. However, I now received this mail after the board has ended my committee membership per request.
Following the link in the mail to unsubscribe, I only see the committee page without unsubscribe option.

I am not bothered by these mails, so this isn't very urgent. However, since it's a bug, I might not be the only one, and I can imagine you'd like the website to be free of bugs🕷️🐜🦗🐝 

Thank you very much!

**Comment by thijsdortmann** [comment]
We'll remove you from the reminder mails. We'll also add automatically removing reminder subscriptions.

**Comment by jonathanjuursema** [comment]
So I've checked, and this [has already been implemented since introducing the Helper Reminder mails](https://github.com/saproto/saproto/commit/03014feb5e34aaf90c507f9cefd930c605757e7a#diff-9958556ae7371942183ca5a9c96221edR205). I'm not quite sure what happened in your case (maybe the request got cut off before that line) but it seems to be a one off event. If this happens again (or if someone else has the same issue) feel free to re-open this.

**Comment by renskruining** [comment]
Not sure what actions have been taken, but I am still getting the e-mails  =/
