### ISSUE TITLE
GoD helper messages

### ISSUE THREAD

**Issue by Vlieking** [saproto/saproto#987]
Hello there, 

We would like to add people from GoD to events as helpers without the committee all getting a helper e-mail, as getting drafters is managed by the TIPcie. 

Kind regards, 

Mick

**Comment by jonathanjuursema** [comment]
Hey! What you're describing is not how the helper system is meant to be used. It would be very impractical to rewrite the helper system specifically for one committee. If the helper system is not working for you, would it be an option to just not use the helper system? As you mention, the TIPcie manages drafters, so it would not be necessary to indicate drafters on the site. As far as I know this has worked since introducing the helper system on the site. What has changed now?

**Comment by Vlieking** [comment]
Hai, thanks for the quick reply.

The reason we wanted to be able to this was to make it easier for Sanne to
see who drafted when, since drafters get discounts on food. Also because
people wanted to be able to see who drafts a drink, for some reason.

Kind regards,

**Comment by jonathanjuursema** [comment]
So it would work for you just to be able to disable committee helper e-mails for a specific committee? Do we need to disable all e-mails, or just the "hey someone indicated there's helpers needed" e-mails?

**Comment by Vlieking** [comment]
Yes, the last option, so just for helper e-mails, would work.

Thanks in advance!

**Comment by thijsdortmann** [comment]
We'll implement this by adding the option to disable the 'your help is needed' emails for a committee. This can then be disabled for the GoD.
